# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'yesh01b/docker-webapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deply
  displayName: Deploy Container
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Pay-As-You-Go (c4c44e31-c0c8-401b-824e-3fba6c4e6b68)'
        appName: 'webapp-test'
        containers: 'yesh01b/docker-webapp'